name: Publish
on:
  release:
    types: [created]

jobs:

  publish-crates:
    name: Publish to Crates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v5

      - name: Install Rust
        run: rustup toolchain add --profile=minimal stable

      - name: Publish to Crates
        run: cargo publish --token ${{ secrets.CRATES_TOKEN }}
        env:
          RUST_BACKTRACE: "1"